.Dd 2015
.Dt SANDBLAST 1
.Os 
.Sh NAME
.Nm sandblast
.Nd the missing simple container tool for FreeBSD
.Sh SYNOPSIS
.Nm
.Op Fl O Ar stdout
.Op Fl E Ar stderr
.Op Fl v
.Ar config-file
.Sh DESCRIPTION
.Nm
runs a process described by the
.Ar config-file
in a FreeBSD jail.
It runs applications in a lightweight, ephemeral way, without system-wide config files.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl O Ar stdout
The file to redirect the spawned process's stdout to.
.It Fl E Ar stderr
The file to redirect the spawned process's stderr to.
.It Fl v
Enable verbose logging
.It Ar config-file
The JSON file that describes the desired sandbox environment.
.El
.Sh JSON CONFIG FILE STRUCTURE
.Bl -tag -width indent
.It Em ipv4 No :: Sy string
The IPv4 address for the jail.
.It Em hostname No :: Sy string
The jail hostname.
.It Em jailname No :: Sy string
The jailname.
Optional, will be based on the hostname (with some character replacements) by default.
.It Em process No :: Sy string
The source of the script that will be executed inside of the jail.
Usually begins with #!/bin/sh -- but you can use any interpreter that's available inside of the jail.
.El
.Sh AUTHORS
.An "Greg V" Aq greg@unrelenting.technology
.Sh LICENSE
Sandblast is available under the ISC license.
