#!/bin/sh

case "$1" in
	start)
		mkdir -p "`dirname "$SANDBLAST_PATH$DESTINATION"`"
		exec cp -f "$SOURCE" "$SANDBLAST_PATH$DESTINATION"
		;;
	stop)
		exec rm -f "$SANDBLAST_PATH$DESTINATION"
		;;
	*) echo "Invalid command $1" ;;
esac
