#!/bin/sh

: ${CPU="50"}
: ${CPU_HARD="55"}
: ${RAM="512M"}
: ${SWAP="512M"}
: ${FILES="4096"}

case "$1" in
	start)
		rctl -a "jail:$SANDBLAST_JAILNAME:pcpu:sigterm=$CPU"
		rctl -a "jail:$SANDBLAST_JAILNAME:pcpu:sigkill=$CPU_HARD"
		rctl -a "jail:$SANDBLAST_JAILNAME:memoryuse:deny=$RAM"
		rctl -a "jail:$SANDBLAST_JAILNAME:swapuse:deny=$SWAP"
		rctl -a "jail:$SANDBLAST_JAILNAME:openfiles:deny=$FILES"
		;;
	stop)
		exec rctl -r "jail:$SANDBLAST_JAILNAME"
		;;
	*) echo "Invalid command $1" ;;
esac
