#!/bin/sh

: ${MODE="ro"}
: ${DESTINATION=""}

TARGET="$SANDBLAST_PATH$DESTINATION"

case "$1" in
	start)
		mkdir -p "$TARGET"
		if mount | grep "$TARGET " >/dev/null; then
			exec mount_unionfs -o noatime -o copymode=transparent -o "$MODE" "$SOURCE" "$TARGET"
		else
			exec mount_nullfs -o "$MODE" "$SOURCE" "$TARGET"
		fi
		;;
	stop)
		exec umount -f "$TARGET"
		;;
	*) echo "Invalid command $1" ;;
esac
